### ISSUE TITLE
Al met al

### ISSUE THREAD

**Issue by vasilisvg** [JesperHonders/hva-css-minor#7]
Het ziet er tof uit! Je hebt een paar erg leuke details toegevoegd! Mooi man! Let nog even (naast de issues) op de volgende dingen:

## Een “echte” site

Kijk eens of je hier een *echte* site van kan maken. Lukt het je om alle elementen op een logische manier te tonen? Het mag op één pagina, maar ook op meerdere pagina's. Het onderwerp mag je natuurlijk zelf weten.

**Comment by BaardMoeder** [comment]
Ga ik zeker doen!
